main: me.nort721.secureidentity.SecureIdentity
version: Build 0
name: SecureIdentity
author: Nort721
description: Helps you secure the identity of your players and keep permissions in the right hands

commands:
  SecureIdentity:
    description: Base command
    aliases: [si]